### ISSUE TITLE
Document the capability to remind other users

### ISSUE THREAD

**Issue by mark-strasser-nnl** [agrc/create-reminder-action#211]
All of the documentation says "/remind me".  Add an example to the README.md of reminding a GitHub user by name instead of using "me".

```
/remind steveoh tomorrow to fix the left handed fumbling
```

It will still let you know it scheduled the reminder, but will ping the GitHub user name instead.

### Relevant code

It's awesome it already supports this implicitly.

https://github.com/agrc/create-reminder-action/blob/922893a5705067719c4c4751843962f56aabf5eb/utilities.js#L39

**Comment by steveoh** [comment]
This sounds great to me. I'd appreciate if you would submit a pr with the doc improvements you are suggesting.

**Comment by stdavis** [comment]
/remind @steveoh that this is just a test tomorrow
