### ISSUE TITLE
`Create Reminder` step fails on pull requests

### ISSUE THREAD

**Issue by kublaios** [agrc/create-reminder-action#83]
When I run the `/remind` command on an issue, it sets the reminder, adds the label, then posts the comment to verify that the reminder is set. However, on PRs, it fails to do the last one (posting the comment). When I checked the job's logs, I've seen the following error:
```
  (node:1464) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null
      at addReminderToBody (/home/runner/work/_actions/agrc/create-reminder-action/v1.1.1/webpack:/create-reminder-action/utilities.js:48:1)
      at updateIssue (/home/runner/work/_actions/agrc/create-reminder-action/v1.1.1/webpack:/create-reminder-action/index.js:22:1)
      at run (/home/runner/work/_actions/agrc/create-reminder-action/v1.1.1/webpack:/create-reminder-action/index.js:78:1)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  (node:1464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:1464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm testing the actions on a public repo on which the error can be seen from [here](https://github.com/kublaios/github-actions-reminders/runs/4957056014?check_suite_focus=true).

**Comment by steveoh** [comment]
that error points to 

https://github.com/agrc/create-reminder-action/blob/v1/utilities.js#L48

which then means that your pull request body is empty. I think we can guard against that. 

Thanks for the report!

**Comment by kublaios** [comment]
![It's alive!](https://media.giphy.com/media/d3Kq5w84bzlBLVDO/giphy.gif)

That was fast, thank you! I can verify that [it works](https://github.com/kublaios/github-actions-reminders/pull/2). Now I need to find a way to trigger reminders on merged PRs :)

**Comment by steveoh** [comment]
Will you update your test repo to use https://github.com/agrc/create-reminder-action/commit/72569089eed4baead9e6fa7613ab51534cd1fba3 and see how it handles an empty issue/pr body please.

**Comment by steveoh** [comment]
I added a test that verifies it _should_ work, but since you have it all set up, it would be a nice test to see in the wild.

thanks @kublaios

**Comment by kublaios** [comment]
Interesting, I'm having the same issue. I tried both the commit you mentioned and the branch.
```
Run agrc/create-reminder-action@fix/83
parsing reminder
add label
update issue
  (node:1447) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null
      at addReminderToBody (/home/runner/work/_actions/agrc/create-reminder-action/fix/83/webpack:/create-reminder-action/utilities.js:48:1)
      at updateIssue (/home/runner/work/_actions/agrc/create-reminder-action/fix/83/webpack:/create-reminder-action/index.js:22:1)
      at run (/home/runner/work/_actions/agrc/create-reminder-action/fix/83/webpack:/create-reminder-action/index.js:78:1)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  (node:1447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:1447) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
