### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by tblanarik** [agrc/create-reminder-action#91]
Hey all! This is an awesome Action, but I'm running into a bug. It worked once in an issue:
![image](https://user-images.githubusercontent.com/1554630/155422902-04f218f5-ca68-4981-9f21-15329a569ce6.png)

but in subsequent attempts, I get the following error:
![image](https://user-images.githubusercontent.com/1554630/155422978-bfe8a639-177f-4908-952b-65354bacd8fa.png)

It adds the `reminder` label, but never closes the loop:
![image](https://user-images.githubusercontent.com/1554630/155423044-d05d2831-fc9c-4dee-9ac7-dede408730f2.png)

Any thoughts? Anything I can provide to help debug?

**Comment by tblanarik** [comment]
I know what's going on, but I don't know how to fix it (yet).

^ This happens when the body of the issue is empty. I create many empty-body issues in my personal repo as a "To Do" list. 😆

**Comment by tblanarik** [comment]
And silly me, I see that this was already fixed with this PR:
- https://github.com/agrc/create-reminder-action/pull/84

**Comment by steveoh** [comment]
The is a two step action btw and is explained in the readme.
